# Generated by Django 3.0.3 on 2020-09-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PFASMsgRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=140)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
